=== FausVillegas/DB_SolvdJavaProject/src/main/resources/users.xsd
<?xml version="1.0" encoding="utf-8"?>

<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="users">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="user">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name" type="xs:string" />
                            <xs:element name="lastName" type="xs:string" />
                            <xs:element name="age" type="xs:int" />
                            <xs:element name="contactInformation">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="email" type="xs:string" />
                                        <xs:element name="phoneNumber" type="xs:long" />
                                    </xs:sequence>
                                    <xs:attribute name="id" type="xs:int" use="required" />
                                </xs:complexType>
                            </xs:element>
                            <xs:element name="phones">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element name="phone">
                                            <xs:complexType>
                                                <xs:sequence>
                                                    <xs:element name="brand" type="xs:string" />
                                                    <xs:element name="model" type="xs:string" />
                                                    <xs:element name="operatingSystem">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="name" type="xs:string" />
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:int" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                    <xs:element name="battery">
                                                        <xs:complexType>
                                                            <xs:sequence>
                                                                <xs:element name="capacityMah" type="xs:float" />
                                                            </xs:sequence>
                                                            <xs:attribute name="id" type="xs:int" use="required" />
                                                        </xs:complexType>
                                                    </xs:element>
                                                </xs:sequence>
                                                <xs:attribute name="id" type="xs:int" use="required" />
                                            </xs:complexType>
                                        </xs:element>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:int" use="required" />
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== FausVillegas/DB_SolvdJavaProject/src/main/resources/users.xml
<?xml version="1.0" encoding="UTF-8"?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="users.xsd">
    <user id="1">
        <name>Fausto</name>
        <lastName>Villegas</lastName>
        <age>19</age>
        <contactInformation id="1">
            <email>faustovillegas2015@gmail.com</email>
            <phoneNumber>2222222222</phoneNumber>
        </contactInformation>
        <phones>
            <phone id="1">
                <brand>Samsung</brand>
                <model>S22</model>
                <operatingSystem id="1">
                    <name>Android 13</name>
                </operatingSystem>
                <battery id="6">
                    <capacityMah>5500</capacityMah>
                </battery>
            </phone>
        </phones>
    </user>
</users>
